### ISSUE TITLE
Support to promote the latest release to a particular environment

### ISSUE THREAD

**Issue by LinuxSuRen** [kubesphere-sigs/ks-releaser#53]
Below is a regular [kustomize](https://github.com/kubernetes-sigs/kustomize) YAML file:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

images:
- name: ghcr.io/kubesphere-sigs/ks-releaser
  newName: ghcr.io/kubesphere-sigs/ks-releaser
  newTag: v0.0.13

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
```

I'd like to suggest having a feature to promote the latest release to a particular environment. Such as, if `ks-releaser` project just released `v0.0.14`, then create a PR to bump the version from `v0.0.13` to `v0.0.14`.

Such as, we can have the following CRD:
```yaml
kind: Promote
spec:
  releaser: xxx
  git: xxx
  environments:
  - name: int
     path: int
     policy: automated | pr
```
